# Generated by Django 2.2 on 2019-05-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=200)),
                ('limit', models.IntegerField()),
                ('sort_by', models.CharField(max_length=200)),
                ('subreddit', models.CharField(max_length=200)),
                ('batch_id', models.CharField(max_length=200)),
                ('submission_id', models.CharField(max_length=200)),
                ('scheduled_time', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.TextField(db_column='jobId', unique=True)),
                ('jobtype', models.TextField(db_column='jobType')),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('sortby', models.TextField(blank=True, db_column='sortBy', null=True)),
                ('subreddit', models.TextField(blank=True, null=True)),
                ('batchid', models.TextField(blank=True, db_column='batchId', null=True)),
                ('submissionid', models.TextField(blank=True, db_column='submissionId', null=True)),
                ('scheduledtime', models.TextField(db_column='scheduledTime')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'process_queue',
            },
        ),
        migrations.CreateModel(
            name='SubmissionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionid', models.TextField(db_column='submissionId')),
                ('batchid', models.TextField(db_column='BatchId')),
                ('created', models.TextField()),
                ('number_1_hour', models.TextField(blank=True, db_column='1_hour', null=True)),
                ('number_2_hour', models.TextField(blank=True, db_column='2_hour', null=True)),
                ('number_5_hour', models.TextField(blank=True, db_column='5_hour', null=True)),
                ('number_8_hour', models.TextField(blank=True, db_column='8_hour', null=True)),
                ('number_12_hour', models.TextField(blank=True, db_column='12_hour', null=True)),
                ('number_24_hour', models.TextField(blank=True, db_column='24_hour', null=True)),
            ],
            options={
                'db_table': 'submission_data',
            },
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionid', models.TextField(blank=True, db_column='SubmissionID', null=True)),
                ('submissionname', models.TextField(blank=True, db_column='SubmissionName', null=True)),
                ('batchid', models.TextField(blank=True, db_column='BatchId', null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
    ]
