# Generated by Django 2.2 on 2019-05-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmachart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessQueue',
        ),
        migrations.DeleteModel(
            name='SubmissionData',
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
    ]
