# Generated by Django 2.2 on 2019-05-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmachart', '0003_processqueue_submissiondata_submissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='submissiondata',
            table=None,
        ),
    ]
