# Generated by Django 2.2 on 2019-05-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmachart', '0004_auto_20190520_2334'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='processqueue',
            table=None,
        ),
        migrations.AlterModelTable(
            name='submissions',
            table=None,
        ),
    ]
