# Generated by Django 2.2 on 2019-05-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmachart', '0006_auto_20190521_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='codyexample',
        ),
    ]
