# Generated by Django 2.2 on 2019-07-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmachart', '0009_auto_20190522_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortby', models.TextField(blank=True, db_column='sortBy', null=True)),
            ],
        ),
    ]
