# Generated by Django 2.2 on 2019-07-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmachart', '0010_sortmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortmethod',
            name='sortby',
            field=models.CharField(choices=[('top', 'Top'), ('new', 'New'), ('controversial', 'Controversial')], max_length=25),
        ),
    ]
